name: Build and Push Docker Image

on:
  push:
    branches:
      - stage

env:
  GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/avansoft/flickit-platform:stage ./backend
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/avansoft/flickit-platform:stage
