name: Update cms/master

on:
  push:
    branches:
      - main
      
env:
  GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.GH_PACKAGES_TOKEN }}
          source: 'main'
          target: 'stage'
          webhook_url: #if present add the Slack webhook